parameters:
#    kunstmaan_k_page_part.example.class: Kunstmaan\PagePartBundle\Example

services:
#    kunstmaan_k_page_part.example:
#        class: %kunstmaan_k_page_part.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    kunstmaan_pagepart.pageparts:
        class: Kunstmaan\PagePartBundle\PagePartAdmin\Builder

    kunstmaan_pagepartadmin.factory:
        class: Kunstmaan\PagePartBundle\PagePartAdmin\PagePartAdminFactory

    kunstmaan_pagepartadmin.twig.extension:
        class: Kunstmaan\PagePartBundle\Twig\Extension\PagePartAdminTwigExtension
        tags:
            -  { name: twig.extension }

    kunstmaan_pageparts.twig.extension:
            class: Kunstmaan\PagePartBundle\Twig\Extension\PagePartTwigExtension
            arguments:
                - @doctrine.orm.entity_manager
            tags:
                - { name: twig.extension }
