parameters:
#    kunstmaan_k_page_part.example.class: Kunstmaan\PagePartBundle\Example

services:
#    kunstmaan_k_page_part.example:
#        class: %kunstmaan_k_page_part.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    kunstmaan_pagepart.pageparts:
        class: Kunstmaan\PagePartBundle\PagePartAdmin\Builder

    kunstmaan_pagepartadmin.factory:
        class: Kunstmaan\PagePartBundle\PagePartAdmin\PagePartAdminFactory

    kunstmaan_pagepartadmin.twig.extension:
        class: Kunstmaan\PagePartBundle\Twig\Extension\PagePartAdminTwigExtension
        tags:
            -  { name: twig.extension }

    kunstmaan_pageparts.twig.extension:
        class: Kunstmaan\PagePartBundle\Twig\Extension\PagePartTwigExtension
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }

    kunstmaan_pageparts.edit_node.listener:
        class: Kunstmaan\PagePartBundle\EventListener\NodeListener
        arguments: ["@request", "@doctrine.orm.entity_manager", "@form.factory", "@kunstmaan_pagepartadmin.factory"]
        scope: request
        tags:
            - { name: kernel.event_listener, event: kunstmaan_node.adaptForm, method: adaptForm }

    kunstmaan_pageparts.clone.listener:
        class: Kunstmaan\PagePartBundle\EventListener\CloneListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kunstmaan_admin.postDeepCloneAndSave, method: postDeepCloneAndSave }
